# Example toml file as input for metasyn

dist_providers = ["builtin", "metasyn-disclosure"]

[privacy]
name = "disclosure"
parameters = {partition_size = 11}


[[var]]
name = "PassengerId"
distribution = {unique = true}  # Notice booleans are lower case in .toml files.

[[var]]
name = "Name"
prop_missing = 0.1
description = "Name of the unfortunate passenger of the titanic."
distribution = {implements = "core.faker", parameters = {faker_type = "name", locale = "en_US"}}

[[var]]
name = "Fare"
distribution = {implements = "core.exponential"}

[[var]]
name = "Age"
distribution = {implements = "core.uniform", parameters = {lower = 20, upper = 40}}

[[var]]
name = "Cabin"
distribution = {implements = "core.regex", parameters = {regex_data = "[A-F][0-9]{2,3}"}}
privacy = {name = "disclosure", parameters = {partition_size = 21}}
